name: todays_alba
description: "오늘의 알바:점주와 알바생을 위한 근무 스케줄 및 급여 관리 올인원 서비스"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.4
  provider: ^6.1.1
  dio: ^5.7.0
  platform: ^3.1.5
  shared_preferences: ^2.3.2
  crypto: ^3.0.5
  encrypt: ^5.0.3
  kakao_flutter_sdk: ^1.9.5 # 전체 추가
  kakao_flutter_sdk_user: ^1.9.5 # 카카오 로그인 API 패키지
  kakao_flutter_sdk_share: ^1.9.5 # 카카오톡 공유 API 패키지
  kakao_flutter_sdk_talk: ^1.9.5 # 카카오톡 채널, 카카오톡 소셜, 카카오톡 메시지 API 패키지
  kakao_flutter_sdk_friend: ^1.9.5 # 피커 API 패키지
  kakao_flutter_sdk_navi: ^1.9.5 # 카카오내비 API 패키지
  lottie: ^3.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/font/PretendardVariable.ttf
    - family: HancomMalangMalang
      fonts:
        - asset: assets/font/HancomMalangMalang-Regular.ttf

  assets:
    - assets/images/
    - assets/lottie/
    - .env